# Generated by Django 6.0.5 on 2026-05-12 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_remove_profile_average_rating_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('services', models.TextField(blank=True, help_text='List the services you offer')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/workshops/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_profile', to='account.artisanprofile')),
            ],
        ),
    ]
