# Generated by Django 6.0.5 on 2026-05-15 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_alter_category_id_alter_portfolioimage_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/completed_projects/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_projects', to='workshop.workshopprofile')),
            ],
            options={
                'ordering': ['-is_featured', '-date_completed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompletedProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/completed_project_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_before', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pair_group', models.IntegerField(default=0, help_text='Group images into pairs by number (optional)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workshop.completedproject')),
            ],
            options={
                'ordering': ['pair_group', '-is_before', '-uploaded_at'],
            },
        ),
    ]
