# Generated by Django 6.0.5 on 2026-05-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_alter_airefinelog_id_alter_request_id_and_more'),
        ('workshop', '0010_completedproject_completedprojectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedproject',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_projects', to='request.request'),
        ),
    ]
