# Generated by Django 5.2.14 on 2026-05-17 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0013_alter_category_id_alter_completedproject_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.CharField(blank=True, help_text='E.g. ~2 hours', max_length=100)),
                ('typical_turnaround', models.CharField(blank=True, help_text='E.g. 3–10 days', max_length=100)),
                ('active_orders', models.CharField(blank=True, help_text='E.g. 2 (available)', max_length=100)),
                ('item_drop_off', models.BooleanField(default=False)),
                ('ships_ksa', models.BooleanField(default=False)),
                ('protection_text', models.TextField(blank=True, help_text='Optional protection / policy text shown to buyers')),
                ('workshop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='workshop.workshopprofile')),
            ],
        ),
    ]
