"""
Django settings for rising_phoenix project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dotenv

dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=da!3*bk)6e&#i+9zl3jykxi1#w^vr3$eu8brjk4a4+_b^t1i&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'account',
    'staff',
    'workshop',
    'request',
    'proposal',
    'phonenumber_field',
    'payment',
    'message',
    'progress',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rising_phoenix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rising_phoenix.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4o-mini')
OPENAI_MODERATION_MODEL = os.getenv('OPENAI_MODERATION_MODEL', 'omni-moderation-latest')
OPENAI_REFINE_TIMEOUT_SECONDS = float(os.getenv('OPENAI_REFINE_TIMEOUT_SECONDS', '15'))
OPENAI_REFINE_RETRIES = int(os.getenv('OPENAI_REFINE_RETRIES', '2'))
OPENAI_REFINE_RETRY_BASE_DELAY_SECONDS = float(os.getenv('OPENAI_REFINE_RETRY_BASE_DELAY_SECONDS', '0.7'))
OPENAI_REFINE_MAX_INPUT_CHARS = int(os.getenv('OPENAI_REFINE_MAX_INPUT_CHARS', '1200'))
OPENAI_REFINE_MAX_OUTPUT_TOKENS = int(os.getenv('OPENAI_REFINE_MAX_OUTPUT_TOKENS', '140'))
OPENAI_REFINE_TEMPERATURE = float(os.getenv('OPENAI_REFINE_TEMPERATURE', '0.5'))

# Rate limiting: max AI refine calls per user per window
OPENAI_REFINE_RATE_LIMIT = int(os.getenv('OPENAI_REFINE_RATE_LIMIT', '10'))
OPENAI_REFINE_RATE_WINDOW_SECONDS = int(os.getenv('OPENAI_REFINE_RATE_WINDOW_SECONDS', '3600'))

# Prompt response cache TTL in seconds (0 disables caching)
OPENAI_REFINE_CACHE_TTL_SECONDS = int(os.getenv('OPENAI_REFINE_CACHE_TTL_SECONDS', '300'))

# Image upload limits
REQUEST_IMAGE_MAX_SIZE_MB = float(os.getenv('REQUEST_IMAGE_MAX_SIZE_MB', '5'))
REQUEST_IMAGE_ALLOWED_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'image/gif']

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_VERIFY_SERVICE_SID = os.getenv("TWILIO_VERIFY_SERVICE_SID")


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_PASSWORD")
EMAIL_TIMEOUT = 10

STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY")
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY")



