# Generated by Django 5.2.13 on 2026-05-16 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('proposal_received', 'New Proposal'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('progress_update', 'Progress Update'), ('comment_added', 'New Feedback'), ('completion_requested', 'Completion Requested'), ('completion_confirmed', 'Project Completed'), ('completion_rejected', 'Completion Sent Back'), ('message_received', 'New Message')], max_length=30),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_proposal_received', models.BooleanField(default=True)),
                ('email_proposal_accepted', models.BooleanField(default=True)),
                ('email_proposal_rejected', models.BooleanField(default=True)),
                ('email_progress_update', models.BooleanField(default=True)),
                ('email_comment_added', models.BooleanField(default=True)),
                ('email_completion_requested', models.BooleanField(default=True)),
                ('email_completion_confirmed', models.BooleanField(default=True)),
                ('email_completion_rejected', models.BooleanField(default=True)),
                ('email_message_received', models.BooleanField(default=True)),
                ('insite_proposal_received', models.BooleanField(default=True)),
                ('insite_proposal_accepted', models.BooleanField(default=True)),
                ('insite_proposal_rejected', models.BooleanField(default=True)),
                ('insite_progress_update', models.BooleanField(default=True)),
                ('insite_comment_added', models.BooleanField(default=True)),
                ('insite_completion_requested', models.BooleanField(default=True)),
                ('insite_completion_confirmed', models.BooleanField(default=True)),
                ('insite_completion_rejected', models.BooleanField(default=True)),
                ('insite_message_received', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
