# Generated by Django 5.2.14 on 2026-05-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_notif_type_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('proposal_received', 'New Proposal'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('progress_update', 'Progress Update'), ('comment_added', 'New Feedback'), ('completion_requested', 'Completion Requested'), ('completion_confirmed', 'Project Completed'), ('completion_rejected', 'Completion Sent Back'), ('message_received', 'New Message'), ('report_received', 'New Report'), ('report_status_update', 'Report Update')], max_length=30),
        ),
    ]
