# Generated by Django 5.2.13 on 2026-05-15 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_contractevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/progress_events/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='progress.contractevent')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
