# Generated by Django 5.2.14 on 2026-05-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_progresscommentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='artisan_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='requester_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending_requester', 'Pending Requester Acceptance'), ('pending_artisan', 'Pending Artisan Acceptance'), ('active', 'Active'), ('in_progress', 'In Progress'), ('completion_requested', 'Completion Requested'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending_artisan', max_length=30),
        ),
    ]
