# Generated by Django 5.2.14 on 2026-05-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_progresscommentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='earnings_recorded',
            field=models.BooleanField(default=False),
        ),
    ]
