# Generated by Django 5.2.14 on 2026-05-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_contract_artisan_accepted_at_and_more'),
        ('progress', '0005_contract_earnings_recorded'),
    ]

    operations = [
    ]
