# Generated by Django 5.2.14 on 2026-05-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_merge_20260517_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending_requester', 'Pending Requester Acceptance'), ('pending_artisan', 'Pending Artisan Acceptance'), ('in_progress', 'In Progress'), ('completion_requested', 'Completion Requested'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending_artisan', max_length=30),
        ),
    ]
