# Generated by Django 5.2.14 on 2026-05-17 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_artisanprofile_id_alter_profile_id_and_more'),
        ('message', '0004_alter_conversation_id_alter_message_id'),
        ('request', '0011_alter_airefinelog_id_alter_request_id_and_more'),
        ('staff', '0006_alter_report_id'),
        ('workshop', '0013_alter_category_id_alter_completedproject_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_reviewed',
        ),
        migrations.AddField(
            model_name='report',
            name='content_type',
            field=models.CharField(choices=[('user', 'User'), ('request', 'Request'), ('portfolio_image', 'Portfolio Image'), ('review', 'Review'), ('message', 'Message')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='message.message'),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_portfolio_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='workshop.portfolioimage'),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='request.request'),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='account.review'),
        ),
        migrations.AddField(
            model_name='report',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('fraud', 'Fraud'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
