# Generated by Django 5.2.14 on 2026-05-16 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentmethod_id_alter_stripecustomer_id'),
        ('progress', '0004_progresscommentimage'),
        ('proposal', '0002_proposalimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='EscrowPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('stripe_payment_method_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='sar', max_length=10)),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='requires_payment_method', max_length=50)),
                ('captured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_payment', to='progress.contract')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_payment', to='proposal.proposal')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
