# Generated by Django 5.2.14 on 2026-05-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentmethod_id_alter_stripecustomer_id'),
        ('payment', '0003_alter_paymentmethod_id_alter_stripecustomer_id_and_more'),
    ]

    operations = [
    ]
