# Generated by Django 6.0.5 on 2026-05-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('woodworking', 'Woodworking'), ('art', 'Art'), ('handmade_gifts', 'Handmade Gifts'), ('fashion_embroidery', 'Fashion & Embroidery'), ('leathercraft', 'Leathercraft'), ('home_decor', 'Home Decor'), ('pottery_ceramics', 'Pottery & Ceramics')], max_length=20),
        ),
    ]
