<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-14 07:37
=======
# Generated by Django 6.0.5 on 2026-05-14 05:21
>>>>>>> 2019db65857daca81b310032e1afa6740004b1b6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_request_image_caption_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airefinelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requestimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
