# Generated by Django 5.2.14 on 2026-05-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_alter_airefinelog_id_alter_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airefinelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requestimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
