# Generated by Django 5.2.14 on 2026-05-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_alter_airefinelog_id_alter_request_id_and_more'),
        ('request', '0010_remove_request_budget_min'),
    ]

    operations = [
    ]
