# Generated by Django 5.2.14 on 2026-05-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_alter_airefinelog_id_alter_request_id_and_more'),
        ('request', '0011_merge_20260517_0848'),
    ]

    operations = [
    ]
