# Generated by Django 6.0.5 on 2026-05-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_artisanprofile_phone_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='reviews_given',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='service_review',
            new_name='reviews_received',
        ),
    ]
