# Generated by Django 6.0.5 on 2026-05-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_artisanprofile_ban_reason_artisanprofile_is_banned_and_more'),
        ('account', '0006_rename_reviewer_review_reviews_given_and_more'),
    ]

    operations = [
    ]
