# Generated by Django 6.0.5 on 2026-05-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_merge_20260513_0824'),
        ('account', '0007_merge_20260513_1014'),
    ]

    operations = [
    ]
