# Generated by Django 6.0.5 on 2026-05-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_merge_20260512_2232'),
        ('account', '0008_merge_20260513_1818'),
    ]

    operations = [
    ]
