# Generated by Django 5.2.14 on 2026-05-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_merge_20260513_1014'),
        ('account', '0009_alter_artisanprofile_id_alter_profile_id_and_more'),
    ]

    operations = [
    ]
