# Generated by Django 5.2.14 on 2026-05-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_merge_20260513_1749'),
        ('account', '0008_merge_20260513_1956'),
        ('account', '0010_merge_20260513_2010'),
    ]

    operations = [
    ]
