# Generated by Django 6.0.5 on 2026-05-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_merge_20260513_2027'),
        ('account', '0012_merge_20260514_0018'),
    ]

    operations = [
    ]
