# Generated by Django 6.0.5 on 2026-05-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_merge_20260515_1900'),
        ('account', '0016_merge_20260515_1931'),
    ]

    operations = [
    ]
