# Generated by Django 5.2.14 on 2026-05-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_artisanprofile_id_alter_profile_id_and_more'),
        ('account', '0017_merge_20260516_1941'),
    ]

    operations = [
    ]
