# Generated by Django 5.2.14 on 2026-05-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_artisanrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='stripe_connected_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
