# Generated by Django 5.2.14 on 2026-05-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_merge_20260517_2104'),
        ('account', '0019_artisanprofile_stripe_connected_account_id'),
    ]

    operations = [
    ]
